version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresLiveCoding
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: liveCode
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
